UPDATE categories SET name = 'Áo Sơ Mi' WHERE slug = 'ao-so-mi';
UPDATE categories SET name = 'Quần Tây' WHERE slug = 'quan-tay';
UPDATE categories SET name = 'Áo Khoác' WHERE slug = 'ao-khoac';
UPDATE categories SET name = 'Phụ Kiện' WHERE slug = 'phu-kien';
UPDATE categories SET name = 'Áo Thun' WHERE slug = 'ao-thun';
UPDATE categories SET name = 'Quần Jean' WHERE slug = 'quan-jean';
UPDATE categories SET name = 'Giày' WHERE slug = 'giay';

UPDATE products SET name = 'Sơ Mi Trắng Egyptian Cotton' WHERE slug = 'SM01';
UPDATE products SET name = 'Sơ Mi Chambray Casual' WHERE slug = 'SM02';
UPDATE products SET name = 'Sơ Mi Sọc Xanh Navy' WHERE slug = 'SM03';
UPDATE products SET name = 'Quần Tây Slim-fit Classic' WHERE slug = 'QT01';
UPDATE products SET name = 'Quần Tây Xếp Ly Cao Cấp' WHERE slug = 'QT02';
UPDATE products SET name = 'Blazer Nam Tailored Navy' WHERE slug = 'AK01';
UPDATE products SET name = 'Overcoat Lông Cừu Camel' WHERE slug = 'AK02';
UPDATE products SET name = 'Áo Khoác Dạ Nữ Thanh Lịch' WHERE slug = 'AK03';
UPDATE products SET name = 'Thắt Lưng Da Bò Classic' WHERE slug = 'PK01';
UPDATE products SET name = 'Túi Da Cao Cấp Classic' WHERE slug = 'PK02';
UPDATE products SET name = 'Đồng Hồ Bạc Tối Giản' WHERE slug = 'PK03';
UPDATE products SET name = 'Cà Vạt Lụa Họa Tiết' WHERE slug = 'PK04';
